
-- Criação das tabelas para o projeto FarmTech (Agricultura Digital)
-- Script compatível com Oracle SQL Developer

CREATE TABLE LOCAL (
    LOCAL_ID NUMBER PRIMARY KEY,
    DESCRICAO_LOCAL VARCHAR2(100)
);

CREATE TABLE TIPO_SENSOR (
    TIPO_SENSOR_ID NUMBER PRIMARY KEY,
    DESCRICAO_TIPO VARCHAR2(50)
);

CREATE TABLE TIPO_APLICACAO (
    TIPO_APLICACAO_ID NUMBER PRIMARY KEY,
    DESCRICAO_APLICACAO VARCHAR2(50)
);

CREATE TABLE SENSOR (
    SENSOR_ID NUMBER PRIMARY KEY,
    TIPO_SENSOR_ID NUMBER,
    LOCAL_ID NUMBER,
    CONSTRAINT FK_SENSOR_TIPO_SENSOR FOREIGN KEY (TIPO_SENSOR_ID) REFERENCES TIPO_SENSOR(TIPO_SENSOR_ID),
    CONSTRAINT FK_SENSOR_LOCAL FOREIGN KEY (LOCAL_ID) REFERENCES LOCAL(LOCAL_ID)
);

CREATE TABLE CULTURA (
    CULTURA_ID NUMBER PRIMARY KEY,
    NOME_CULTURA VARCHAR2(50),
    TIPO_SOLO VARCHAR2(30),
    CICLO_DIAS NUMBER
);

CREATE TABLE LEITURA_SENSOR (
    LEITURA_ID NUMBER PRIMARY KEY,
    DATA_HORA TIMESTAMP,
    VALOR NUMBER,
    SENSOR_ID NUMBER,
    CULTURA_ID NUMBER,
    CONSTRAINT FK_LEITURA_SENSOR FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(SENSOR_ID),
    CONSTRAINT FK_LEITURA_CULTURA FOREIGN KEY (CULTURA_ID) REFERENCES CULTURA(CULTURA_ID)
);

CREATE TABLE APLICACAO (
    APLICACAO_ID NUMBER PRIMARY KEY,
    DATA_HORA TIMESTAMP,
    QUANTIDADE NUMBER,
    TIPO_APLICACAO_ID NUMBER,
    CULTURA_ID NUMBER,
    CONSTRAINT FK_APLICACAO_TIPO FOREIGN KEY (TIPO_APLICACAO_ID) REFERENCES TIPO_APLICACAO(TIPO_APLICACAO_ID),
    CONSTRAINT FK_APLICACAO_CULTURA FOREIGN KEY (CULTURA_ID) REFERENCES CULTURA(CULTURA_ID)
);
